### ISSUE TITLE
Issues with RC2

### ISSUE THREAD

**Issue by nmeed** [nogira/anki-minimal-theme#3]
Just a heads up, I installed RC2 however Anki didn't let the add-on run as it said it's incompatible with .45. 
Also, I don't know if this is specific with RC2 or with the add-on, but for some reason on the main screen  where it shows the number of new and due cards, it also now shows the number of reviews without the label just kind of shoehorned inl. I don't know what that's about, just figured I would mention it.

**Comment by nogira** [comment]
reviews number in main screen is a new default anki feature in 2.1.45

not sure why you can't install, but its probably just because 2.1.45 hasnt officially released so the addon manager site doesnt allow it; you can just copy the files from here into a new folder in the anki addons folder and it should work fine
