### ISSUE TITLE
Using the add-on in Anki 2.1.35

### ISSUE THREAD

**Issue by mateuszschmidt** [nogira/anki-minimal-theme#5]
Hello. Thanks for creating it. I checked it on AnkiWeb and it looks perfect, I love minimalism. Any way to run it on Anki 2.1.35? I need this version, because of the other add-ons I am using. Cheers :)

**Comment by nogira** [comment]
i just updated the versioning number on the addon page so it can run in 2.1.35

it mostly runs fine, but the html/css must have changed somewhere between 2.1.35 and 2.1.43 because the editor buttons are a bit off. i don't have the time to fix it, but you could probably fix it if you just edit the css files in the addon files (tip: [AnkiWebView Inspector](https://ankiweb.net/shared/info/31746032) is very helpful to workout what css classes you need to edit)
